"""Typosquatting checks: lookalike domain permutations (dnstwist), resolved
concurrently, with an optional bounded WHOIS lookup for each registered
lookalike found."""
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed

try:
    import dnstwist
    HAVE_DNSTWIST = True
except ImportError:
    HAVE_DNSTWIST = False

from .constants import RATING_INFO, RATING_MEDIUM, ISSUE_TYPE_TYPOSQUATTING
from .util import HAVE_DNSPYTHON, resolve_ips, _get_dns_resolver, _new_issue
from .whois_lookup import check_whois


def check_typosquatting(domain, asset_id, args):
    issues = []
    if not HAVE_DNSTWIST or not HAVE_DNSPYTHON:
        return issues
    try:
        fuzzer = dnstwist.Fuzzer(domain)
        fuzzer.generate()
        permutations = [p for p in fuzzer.permutations() if p['fuzzer'] != '*original']
    except Exception as e:
        logging.debug("dnstwist permutation generation failed: %s", str(e))
        return issues

    limit = getattr(args, 'typosquat_limit', 0) or 0
    if limit and len(permutations) > limit:
        permutations = permutations[:limit]

    resolver = _get_dns_resolver()

    def _check(perm):
        candidate = perm['domain']
        ips = resolve_ips(candidate)
        if ips:
            return (perm, ips)
        return None

    found = []
    workers = getattr(args, 'typosquat_workers', 30)
    logging.info("Checking [%s] domain permutations for typosquatting against [%s]", len(permutations), domain)
    with ThreadPoolExecutor(max_workers=workers) as pool:
        futures = [pool.submit(_check, perm) for perm in permutations]
        for future in as_completed(futures):
            result = future.result()
            if result:
                found.append(result)

    for perm, ips in found:
        candidate = perm['domain']
        issues.append(_new_issue(
            'typosquat-%s' % candidate, "Potential typosquat domain registered: %s" % candidate,
            "Domain [%s] (variation type: %s) closely resembles [%s] and currently resolves to %s. This could be a legitimately owned defensive registration, an unrelated third party who happens to own a similar name, or an actively malicious lookalike domain being staged/used for phishing, credential harvesting, or brand abuse targeting your users/customers." % (
                candidate, perm['fuzzer'], domain, ips),
            RATING_MEDIUM, asset_id, ISSUE_TYPE_TYPOSQUATTING, object_id=candidate,
            remediation="Investigate the domain (WHOIS/registrant, hosted content, MX records) to determine intent. If it is impersonating your brand or hosting phishing content, report it to the registrar/hosting provider's abuse contact, consider a UDRP/URS domain dispute filing, and add it to any email/web threat block-lists you manage. If it is a domain you legitimately own, no action is required."))

    if found and not getattr(args, 'no_whois', False):
        whois_limit = getattr(args, 'typosquat_whois_limit', 15) or 0
        whois_targets = [perm['domain'] for perm, _ in found]
        if whois_limit and len(whois_targets) > whois_limit:
            whois_targets = whois_targets[:whois_limit]
        with ThreadPoolExecutor(max_workers=min(10, len(whois_targets)) or 1) as pool:
            futures = [pool.submit(check_whois, candidate, asset_id, candidate) for candidate in whois_targets]
            for future in as_completed(futures):
                try:
                    issues.extend(future.result())
                except Exception as e:
                    logging.debug("WHOIS lookup task failed: %s", str(e))

    if not found:
        issues.append(_new_issue(
            'typosquat-none-found', "No typosquatting domains found",
            "Checked [%s] domain-name permutation(s) of [%s] (additions, bitsquatting, homoglyphs, hyphenation, insertion, omission, repetition, transposition, vowel-swap, subdomain/combosquats, etc.) generated by dnstwist, and none currently resolve to an IP address." % (len(permutations), domain),
            RATING_INFO, asset_id, ISSUE_TYPE_TYPOSQUATTING, object_id=domain,
            remediation="No action required now. Lookalike domains can be registered at any time, so consider periodic re-scanning and/or a continuous brand-monitoring service for early detection."))
    return issues

