# Build and publish latest twigs package to pypi

name: twigs build

on:
#  push:
#    branches: [ "master" ]
#    paths:
#      - 'twigs/__init__.py'
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: checkout repo content
        run: pip install twine

      - name: build and publish twigs
        run: python ${GITHUB_WORKSPACE}/setup.py sdist bdist_wheel

      - name: verify package using twine
        run: twine check ${GITHUB_WORKSPACE}/dist/*.whl
        
